### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by firrae** [Tyler-pierce/giza_sphinxsearch#2]
Hi there,

This seems to be right up the alley of what I need. I had been looking for a package similar but I'm curious on this projects status? If its dead do you have an alternative i should look at that maybe you've moved to?

Let me know when you can, thanks.

**Comment by Tyler-pierce** [comment]
Hello
In Elixir/Erlang there is no alternative that has been updated recently that I know of. I still use this project as the interface to sphinx and manticore search haven't changed much. You may want some niceties added but you won't reach a dead-end as you can always fall-back to sending a raw query and this lib will take care of some of the grunt work at least.

I'm still monitoring for any issues and will respond at the least to change requests. If you want to tell me more about your needs happy to let you know if this lib serves them.

**Comment by firrae** [comment]
Awesome. I'll try it out. I'm evaluating Manticore/Sphinx vs. Elastic Cloud for a small app I'm building so I'll let you know if run into anything along the way and work though it as possible.

**Comment by Tyler-pierce** [comment]
Alright good luck and feel free to ask if you have any uncertainty with your tests. You are correct in that it's strength is running smaller/lighter. I've had no troubles myself on EC2 free instance running small indices.
